### ISSUE TITLE
passing an async function into tests, throws syntax error

### ISSUE THREAD

**Issue by lmj0011** [thetutlage/japa#3]
using
**node** v6.9.4
**japa** v1.0.0

trying to use `async` functions as shown in the examples, but get a syntax error.

```js
const test = require('japa')

test.group('API', group => {
  group.beforeEach(() => {

  })

  test('Async test', async (assert) => {
    const result = await new Promise(function (resolve, reject) {
      resolve('done')
    })

    console.log(result)
    assert.isTrue(true)
  })
})
```

```sh
/home/landan/www/adonuxt_test/tests/functional/tests/api.js:28
  test('Async test', async (assert) => {
                           ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireDir (/home/landan/www/adonuxt_test/node_modules/require-dir/index.js:122:33)
    at Object.<anonymous> (/home/landan/www/adonuxt_test/tests/functional/test.js:1:85)
```

**Comment by thetutlage** [comment]
How can japa cause Syntax Error?

**Comment by lmj0011** [comment]
idk, does the `async` function work for you?

I don't see the cause of the error from the code

**Comment by thetutlage** [comment]
async/await is supported from Nodejs 7.0 and also is behind `--harmony-async-await` flag

**Comment by lmj0011** [comment]
https://github.com/thetutlage/japa#installation

```
Japa needs Node.js >= 6.0.0.
```

shouldn't this be

```
Japa needs Node.js >= 6.0.0.
for async function support you'll need Node.js >= 7.0.0. along with the `--harmony-async-await flag`
```

**Comment by thetutlage** [comment]
Nope it does not

**Comment by lmj0011** [comment]
for anyone else who runs into this issue and don't have nodev7 yet, use [co](https://www.npmjs.com/package/co)
